###
POST http://{{host}}/ums/admin/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123123"
}

###
GET http://{{host}}/ums/admin/user/info?token={{auth_token}}
Authorization: Bearer {{auth_token}}

###
GET http://{{host}}/ums/admin/all_roles
Authorization: Bearer {{auth_token}}

